openapi: 3.0.0
info:
  description: ''
  version: 1.0.0
  title: Repository
servers:
- url: http://localhost:9292/
tags:
- name: schemas
paths:
  "/schemas/":
    post:
      tags:
      - schemas
      summary: Adds schema
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                payload: 
                  type: string
      responses:
        '200':
          description: data has been added to repo
          content:
            application/json:
              schema:
                type: object
                properties:
                  hashlink: 
                    type: string
    get:
      tags:
      - schemas
      summary: Finds schema 
      parameters:
      - name: schema
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  payload: 
                    type: string
